name: .NET Core

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./Software
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./Software
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ./Software
