name: build and test

on:
  push:

env:
  DOTNET_VERSION: '8.0.x' # The .NET SDK version to use
jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        cache: true
        cache-dependency-path: '**/packages.lock.json'
    - name: Install dependencies
      run: dotnet restore --locked-mode
      
    - name: Build
      run: dotnet build --configuration Release --no-restore -p:PublishSingleFile=false
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
